name: Build MacOS VST3 Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-upload:
    name: Build and Upload Release Asset
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.1"

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

      - name: Build VST3
        run: cmake --build ${{github.workspace}}/build --target vzzz_VST3 --config Release

      - name: Package VST3
        run: |
          mkdir -p artifact/Vzzz-VST3-MacOS
          cp -r build/vzzz_artefacts/Release/VST3/vzzz.vst3 artifact/Vzzz-VST3-MacOS
          cd artifact
          zip -r ../Vzzz-VST3-MacOS.zip .

      - name: Build Standalone
        run: cmake --build ${{github.workspace}}/build --target vzzz_Standalone --config Release

      - name: Package Standalone
        run: |
          mkdir -p artifact/Vzzz-Standalone-MacOS
          cp -r build/vzzz_artefacts/Release/Standalone/vzzz.app artifact/Vzzz-Standalone-MacOS
          cd artifact
          zip -r ../Vzzz-Standalone-MacOS.zip .

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Vzzz-VST3-MacOS.zip
            Vzzz-Standalone-MacOS.zip
